CREATE TABLE [dbo].[tmpinbo] (
    [IndieningID]                   INT                NOT NULL,
    [IndieningTypeVersieID]         NVARCHAR (15)      NOT NULL,
    [IndieningStatusID]             NVARCHAR (15)      NOT NULL,
    [AttachmentSetID]               INT                NULL,
    [Jaartal]                       INT                NULL,
    [DossierNummer]                 NVARCHAR (200)     NULL,
    [CreateDatum]                   DATETIME           NOT NULL,
    [UpdateDatum]                   DATETIME           NOT NULL,
    [IngediendDatum]                DATETIME           NULL,
    [BeslissingDatum]               DATETIME           NULL,
    [VersieNummer]                  SMALLINT           NOT NULL,
    [SnapshotIndieningID]           INT                NULL,
    [VersieDatum]                   DATETIME           NULL,
    [SnapshotDatum]                 DATETIME           NULL,
    [IndieningSoftDeleted]          BIT                NOT NULL,
    [IndieningType]                 NVARCHAR (500)     NOT NULL,
    [IndieningTypeSoftDeleted]      BIT                NOT NULL,
    [IndieningSchadeID]             INT                NULL,
    [Beschrijving]                  NVARCHAR (200)     COLLATE Latin1_General_CI_AI NULL,
    [IndieningSchadeBasisCode]      NVARCHAR (20)      COLLATE Latin1_General_CI_AI NULL,
    [SchadeBeschrijving]            NVARCHAR (200)     COLLATE Latin1_General_CI_AI NULL,
    [AantalDodelijke]               BIGINT             NULL,
    [AantalLichamelijke]            BIGINT             NULL,
    [LichameljkeLetsels]            BIT                NULL,
    [IndieningLocatieID]            INT                NOT NULL,
    [LocatieTypeID]                 NVARCHAR (15)      NOT NULL,
    [LocatieTypeCode]               NVARCHAR (100)     NOT NULL,
    [LocatieTypeSoftDeleted]        BIT                NOT NULL,
    [PuntLocatieShape]              [sys].[geometry]   NULL,
    [PuntLocatieWKT]                NVARCHAR (MAX)     NULL,
    [PolyLocatieShape]              [sys].[geometry]   NULL,
    [PolyLocatieWKT]                NVARCHAR (MAX)     NULL,
    [LijnLocatieShape]              [sys].[geometry]   NULL,
    [LijnLocatieWKT]                NVARCHAR (MAX)     NULL,
    [LocatieShape]                  [sys].[geometry]   NULL,
    [LocatieWKT]                    NVARCHAR (MAX)     NULL,
    [PlantSoortId]                  INT                NULL,
    [SoortNaam]                     NVARCHAR (20)      COLLATE Latin1_General_CI_AI NULL,
    [DierSoortId]                   NVARCHAR (10)      COLLATE Latin1_General_CI_AI NULL,
    [DierSoortNaam]                 NVARCHAR (20)      NULL,
    [SchadeBedragId]                NVARCHAR (20)      COLLATE Latin1_General_CI_AI NULL,
    [SchadeBedragOmschrijving]      NVARCHAR (100)     COLLATE Latin1_General_CI_AI NULL,
    [DatumVeroorzaakt]              DATETIMEOFFSET (7) NULL,
    [DatumVaststelling]             DATETIMEOFFSET (7) NULL,
    [SchadeRegistratieBeschrijving] NVARCHAR (200)     COLLATE Latin1_General_CI_AI NULL
);

