CREATE TABLE [OOMP].[IndieningBezwaar] (
    [IndieningBezwaarID]                    INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IndieningID]                           INT            NULL,
    [IndieningTypeVersieID]                 NVARCHAR (15)  NOT NULL,
    [AttachmentSetID]                       INT            NULL,
    [IndienerIdentificatie]                 NVARCHAR (50)  NOT NULL,
    [ManagementPlanID]                      INT            NOT NULL,
    [ManagementPlan]                        NVARCHAR (500) NOT NULL,
    [BezwaarNummer]                         INT            NULL,
    [IndieningBezwaarTypeID]                NVARCHAR (15)  NULL,
    [IndieningBezwaarRichtkaartTypeID]      NVARCHAR (15)  NULL,
    [IndieningBezwaarRichtkaartOnderdeelID] NVARCHAR (200) NULL,
    [IndieningBezwaarActieID]               NVARCHAR (15)  NULL,
    [IndieningBezwaarActieDetailID]         NVARCHAR (15)  NULL,
    [BezwaarActieOmschrijving]              NVARCHAR (MAX) NULL,
    [Omschrijving]                          NVARCHAR (MAX) NULL,
    [IndieningBezwaarCategorieID]           NVARCHAR (15)  NULL,
    [IsGelezenGoedgekeurd]                  BIT            DEFAULT ((0)) NOT NULL,
    [CreateDatum]                           DATETIME       NOT NULL,
    [UpdateDatum]                           DATETIME       NOT NULL,
    [SoftDeleted]                           BIT            DEFAULT ((0)) NOT NULL,
    [RowVersion]                            ROWVERSION     NOT NULL,
    CONSTRAINT [PK_IndieningBezwaarID] PRIMARY KEY CLUSTERED ([IndieningBezwaarID] ASC),
    CONSTRAINT [FK_Indiening_AttachmentSet] FOREIGN KEY ([AttachmentSetID]) REFERENCES [IR].[AttachmentSet] ([AttachmentSetID]),
    CONSTRAINT [FK_IndieningBezwaar_Indiening] FOREIGN KEY ([IndieningID]) REFERENCES [IR].[Indiening] ([IndieningID]),
    CONSTRAINT [FK_IndieningBezwaar_IndieningBezwaarCategorie] FOREIGN KEY ([IndieningBezwaarCategorieID]) REFERENCES [OOMP].[IndieningBezwaarCategorie] ([IndieningBezwaarCategorieID]),
    CONSTRAINT [FK_IndieningBezwaar_IndieningBezwaarType] FOREIGN KEY ([IndieningBezwaarTypeID]) REFERENCES [OOMP].[IndieningBezwaarType] ([IndieningBezwaarTypeID]),
    CONSTRAINT [FK_IndieningBezwaar_IndieningTypeVersie] FOREIGN KEY ([IndieningTypeVersieID]) REFERENCES [IR].[IndieningTypeVersie] ([IndieningTypeVersieID])
);

