CREATE TABLE [FF].[AfschotPlanGrofWild] (
    [IndieningID]       INT        NOT NULL,
    [Jaartal]           INT        NOT NULL,
    [Wildzwijn]         BIT        CONSTRAINT [DF_AfschotPlanGrofWild_Wildzwijn] DEFAULT ((0)) NOT NULL,
    [Edelhert]          BIT        CONSTRAINT [DF_AfschotPlanGrofWild_Edelhert] DEFAULT ((0)) NOT NULL,
    [Damhert]           BIT        CONSTRAINT [DF_AfschotPlanGrofWild_Damhert] DEFAULT ((0)) NOT NULL,
    [Moeflon]           BIT        CONSTRAINT [DF_AfschotPlanGrofWild_Moeflon] DEFAULT ((0)) NOT NULL,
    [Ree]               BIT        CONSTRAINT [DF_AfschotPlanGrofWild_Ree] DEFAULT ((0)) NOT NULL,
    [WildzwijnJI]       INT        NULL,
    [WildzwijnJIminus1] INT        NULL,
    [WildzwijnJIminus2] INT        NULL,
    [WildzwijnJIminus3] INT        NULL,
    [EdelhertJI]        INT        NULL,
    [EdelhertJIminus1]  INT        NULL,
    [EdelhertJIminus2]  INT        NULL,
    [EdelhertJIminus3]  INT        NULL,
    [DamhertJI]         INT        NULL,
    [DamhertJIminus1]   INT        NULL,
    [DamhertJIminus2]   INT        NULL,
    [DamhertJIminus3]   INT        NULL,
    [MoeflonJI]         INT        NULL,
    [MoeflonJIminus1]   INT        NULL,
    [MoeflonJIminus2]   INT        NULL,
    [MoeflonJIminus3]   INT        NULL,
    [ReebokJI]          INT        NULL,
    [ReebokJIminus1]    INT        NULL,
    [ReebokJIminus2]    INT        NULL,
    [ReebokJIminus3]    INT        NULL,
    [ReegeitJI]         INT        NULL,
    [ReegeitJIminus1]   INT        NULL,
    [ReegeitJIminus2]   INT        NULL,
    [ReegeitJIminus3]   INT        NULL,
    [ReekitsJI]         INT        NULL,
    [ReekitsJIminus1]   INT        NULL,
    [ReekitsJIminus2]   INT        NULL,
    [ReekitsJIminus3]   INT        NULL,
    [SoftDeleted]       BIT        CONSTRAINT [DF_AfschotPlanGrofWild_SoftDeleted] DEFAULT ((0)) NOT NULL,
    [RowVersion]        ROWVERSION NOT NULL,
    CONSTRAINT [PK_AfschotPlanGrofWild] PRIMARY KEY CLUSTERED ([IndieningID] ASC),
    CONSTRAINT [PK_AfschotPlanGrofWild_Indiening] FOREIGN KEY ([IndieningID]) REFERENCES [IR].[Indiening] ([IndieningID])
);

