CREATE TABLE [FF].[MeldingAfschotDier] (
    [MeldingAfschotDierID]  INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [IndieningID]           INT            NOT NULL,
    [Datum]                 DATETIME       NULL,
    [Tijdstip]              NVARCHAR (50)  NULL,
    [Xcoordinaat]           NVARCHAR (50)  NULL,
    [Ycoordinaat]           NVARCHAR (50)  NULL,
    [GemeenteNaam]          NVARCHAR (100) NULL,
    [PostCode]              NVARCHAR (15)  NULL,
    [GemeenteNisCode]       NVARCHAR (15)  NULL,
    [LabelNummer]           NVARCHAR (50)  NOT NULL,
    [GroepID]               NVARCHAR (15)  NULL,
    [AantalDieren]          INT            NULL,
    [LeeftijdDierID]        NVARCHAR (15)  NULL,
    [GeslachtDierID]        NVARCHAR (15)  NULL,
    [AantalEmbryos]         INT            NULL,
    [IsAantalEmbryosBekend] BIT            CONSTRAINT [DF_MeldingAfschotDier_IsAantalEmbryosBekend] DEFAULT ((0)) NOT NULL,
    [Gewicht]               DECIMAL (4, 1) NULL,
    [Stalen]                NVARCHAR (MAX) NULL,
    [LengteOnderkaakLinks]  INT            NULL,
    [LengteOnderkaakRechts] INT            NULL,
    [IsDierenarts]          BIT            CONSTRAINT [DF_MeldingAfschotDier_IsDierenarts_1] DEFAULT ((0)) NULL,
    [NaamDierenarts]        NVARCHAR (50)  NULL,
    [VoornaamDierenarts]    NVARCHAR (50)  NULL,
    [OrdeNummerDierenarts]  NVARCHAR (5)   NULL,
    [OpmerkingDierenarts]   NVARCHAR (100) NULL,
    [Opmerkingen]           NVARCHAR (200) NULL,
    [PuntLocatieTypeID]     INT            NULL,
    [SoftDeleted]           BIT            CONSTRAINT [DF_MeldingAfschotDier_SoftDeleted] DEFAULT ((0)) NOT NULL,
    [RowVersion]            ROWVERSION     NOT NULL,
    [LengteDier]            INT            NULL,
    [LengteDierBekend]      BIT            DEFAULT ((0)) NULL,
    [GewichtTypeID]         NVARCHAR (15)  NULL,
    [GewichtDierBekend]     BIT            DEFAULT ((0)) NULL,
    CONSTRAINT [PK_MeldingAfschotDier] PRIMARY KEY CLUSTERED ([MeldingAfschotDierID] ASC),
    CONSTRAINT [FK_MeldingAfschotDier_Indiening] FOREIGN KEY ([IndieningID]) REFERENCES [IR].[Indiening] ([IndieningID]),
    CONSTRAINT [FK_MeldingAfschotDier_PuntLocatieType] FOREIGN KEY ([PuntLocatieTypeID]) REFERENCES [GIS].[LocatiePuntPrecisieType] ([LocatiePuntPrecisieTypeID])
);

