CREATE TABLE [FF].[WildSchade] (
    [IndieningID]                        INT            NOT NULL,
    [DossierNummer]                      NVARCHAR (10)  NULL,
    [DossierNummerVolgNummer]            INT            NULL,
    [Firma]                              NVARCHAR (200) NULL,
    [IBAN]                               NVARCHAR (34)  NULL,
    [BIC]                                NVARCHAR (11)  NULL,
    [BTWNummer]                          NVARCHAR (20)  NULL,
    [LandbouwerNummer]                   NVARCHAR (20)  NULL,
    [HoedanigheidActiviteit]             NVARCHAR (15)  NULL,
    [SchadeTypeID]                       NVARCHAR (15)  NOT NULL,
    [BeschrijvingSchade]                 NVARCHAR (800) NULL,
    [VaststellingDatum]                  DATETIME       NULL,
    [OorzaakDatum]                       DATETIME       NULL,
    [AfkomstDieren]                      NVARCHAR (20)  NULL,
    [AfkomstDierenNaamGebied]            NVARCHAR (800) NULL,
    [SchadeBedrag]                       NVARCHAR (800) NULL,
    [Xcoordinaat]                        NVARCHAR (50)  NULL,
    [Ycoordinaat]                        NVARCHAR (50)  NULL,
    [MaatregelenGenomen]                 NVARCHAR (50)  NULL,
    [CheckVerzamelaanvraag]              BIT            NULL,
    [CheckTabelPercelen]                 BIT            NULL,
    [CheckLiggingsplan]                  BIT            NULL,
    [CheckPachtOfHuurovereenkomst]       BIT            NULL,
    [CheckIdentificatieRegisterLandbouw] BIT            NULL,
    [CheckFoto]                          BIT            NULL,
    [AantalFotos]                        INT            NULL,
    [CheckAndereBewijsstukken]           BIT            NULL,
    [PuntLocatieTypeID]                  INT            NULL,
    [SoftDeleted]                        BIT            DEFAULT ((0)) NOT NULL,
    [RowVersion]                         ROWVERSION     NOT NULL,
    CONSTRAINT [PK_WildSchade] PRIMARY KEY CLUSTERED ([IndieningID] ASC),
    CONSTRAINT [FK_WildSchade_Indiening] FOREIGN KEY ([IndieningID]) REFERENCES [IR].[Indiening] ([IndieningID]),
    CONSTRAINT [FK_Wildschade_PuntLocatieType] FOREIGN KEY ([PuntLocatieTypeID]) REFERENCES [GIS].[LocatiePuntPrecisieType] ([LocatiePuntPrecisieTypeID]),
    CONSTRAINT [FK_Wildschade_SchadeType] FOREIGN KEY ([SchadeTypeID]) REFERENCES [FF].[SchadeType] ([SchadeTypeID])
);

