CREATE TABLE [Verkennota].[IndieningVerkenningsnota] (
    [IndieningID]                               INT            NOT NULL,
    [DossierTypeID]                             NVARCHAR (70)  NULL,
    [BijzondereSoorten]                         NVARCHAR (MAX) NULL,
    [EcologischeInvloed]                        NVARCHAR (MAX) NULL,
    [EcologischeSwot]                           NVARCHAR (MAX) NULL,
    [EcologischePotentie]                       NVARCHAR (MAX) NULL,
    [EcologischeVisie]                          NVARCHAR (MAX) NULL,
    [EcologischeActueleToestand]                NVARCHAR (MAX) NULL,
    [EconomischeInvloed]                        NVARCHAR (MAX) NULL,
    [EconomischeSwot]                           NVARCHAR (MAX) NULL,
    [EconomischePotentie]                       NVARCHAR (MAX) NULL,
    [EconomischeVisie]                          NVARCHAR (MAX) NULL,
    [SocialeInvloed]                            NVARCHAR (MAX) NULL,
    [SocialeSwot]                               NVARCHAR (MAX) NULL,
    [SocialePotentie]                           NVARCHAR (MAX) NULL,
    [SocialeVisie]                              NVARCHAR (MAX) NULL,
    [EigendomTypeID]                            NVARCHAR (15)  NULL,
    [ProcesgestuurdeNatuurVegetatieEvolutie]    NVARCHAR (MAX) NULL,
    [ProcesgestuurdeNatuurVegetatieHuidig]      NVARCHAR (MAX) NULL,
    [OntwikkeldeVegetatie]                      NVARCHAR (MAX) NULL,
    [OntwikkeldeVegetatieTerreinGeschiktheid]   NVARCHAR (MAX) NULL,
    [GeschiktLeefgebiedVegetatie]               NVARCHAR (MAX) NULL,
    [GeschiktLeefgebiedTerreinGeschiktheid]     NVARCHAR (MAX) NULL,
    [BiologischeDiversiteitVegetatie]           NVARCHAR (MAX) NULL,
    [BiologischeDiversiteitTerreinGeschiktheid] NVARCHAR (MAX) NULL,
    [DoelmatigheidstoetsTypeID]                 NVARCHAR (MAX) NULL,
    [InschattingTerreinDoelstelling]            NVARCHAR (MAX) NULL,
    [DrieFunctiesTypeID]                        NVARCHAR (15)  NULL,
    [DrieFunctiesAndere]                        NVARCHAR (MAX) NULL,
    [DoelstellingTypeID]                        NVARCHAR (15)  NULL,
    [DoelstellingAndere]                        NVARCHAR (MAX) NULL,
    [DrieFunctiesInvulling]                     NVARCHAR (MAX) NULL,
    [IngedeeldBeheereenheidTypeID]              NVARCHAR (15)  NULL,
    [InzageBeheerplan]                          NVARCHAR (MAX) NULL,
    [LiggingOpmerkingen]                        NVARCHAR (MAX) NULL,
    [GlobaalKaderOpmerkingen]                   NVARCHAR (MAX) NULL,
    [IsNaarWaarheid]                            BIT            DEFAULT ((0)) NOT NULL,
    [IsOpErewoordGevolmachtigd]                 BIT            DEFAULT ((0)) NOT NULL,
    [IsOndertekendAkkoordEigendommen]           BIT            DEFAULT ((0)) NOT NULL,
    [IsKennisErfdienstbaarheid]                 BIT            DEFAULT ((0)) NOT NULL,
    [IsAanvraagGoedkeuringNBH]                  BIT            DEFAULT ((0)) NOT NULL,
    [OndertekeningDatum]                        DATETIME       NULL,
    [SoftDeleted]                               BIT            DEFAULT ((0)) NOT NULL,
    [RowVersion]                                ROWVERSION     NOT NULL,
    PRIMARY KEY CLUSTERED ([IndieningID] ASC),
    CONSTRAINT [FK_IndieningVerkenningsnota_Indiening] FOREIGN KEY ([IndieningID]) REFERENCES [IR].[Indiening] ([IndieningID])
);

